name: jt_preferences
description: Json based key-value storage with AES encryption support. Supported data types are `int`, `double`, `bool`, `String` and `Writable object`.
version: 4.0.3
homepage: "https://github.com/xaldarof/jt_preferences"

environment:
  sdk: '>=2.19.2 <3.0.0'


dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

dependencies:
  encrypt: ^5.0.1
  get_it: ^7.2.0
